[font]
size = 12.0

[font.bold]
family = "PragmataPro"
style = "Bold"

[font.bold_italic]
family = "PragmataPro"
style = "Bold Italic"

[font.italic]
family = "PragmataPro"
style = "Italic"

[font.normal]
family = "PragmataPro"
style = "Regular"

[shell]
args = ["--login"]
program = "/bin/zsh"
