controller_name: X-TOUCH MINI
bindings:

  - name: alsa_output.usb-Apple__Inc._USB-C_to_3.5mm_Headphone_Jack_Adapter_DWH211708ZLJKLTAN-00.analog-stereo
    type: sink
    set_volume: 1
    toggle_mute: 8
    set_default: 16

  - name: alsa_output.pci-0000_00_1f.3.iec958-stereo
    type: sink
    set_volume: 2
    toggle_mute: 9
    set_default: 17

  - name: alsa_output.pci-0000_03_00.1.hdmi-stereo-extra2
    type: sink
    set_volume: 3
    toggle_mute: 10
    set_default: 18

  - name: alsa_output.usb-Bose_Bose_USB_Link_082063Z12610201AE-00.iec958-stereo
    type: sink
    set_volume: 4
    toggle_mute: 11
    set_default: 19

  - name: alsa_input.usb-Antlion_Audio_Antlion_USB_Microphone-00.mono-fallback
    type: source
    set_volume: 8
    toggle_mute: 15
    set_default: 23

